name: Static code checkers

on: [push]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/base.txt
        pip install mypy
    - name: Create a dummy data.py
      run: cp data.py-dist data.py
    - name: Install additional typing data and check with mypy
      run: mypy --install-types --non-interactive lib/ conftest.py pkgfixtures.py tests/

  pyright:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/base.txt
        pip install pyright
    - name: Create a dummy data.py
      run: cp data.py-dist data.py
    - name: Check with pyright
      run: pyright lib/ conftest.py pkgfixtures.py # tests/
