name: Static code checkers

on: [push]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.7.x"
    - name: Install dependencies
      run: uv sync --frozen
    - name: Create a dummy data.py
      run: cp data.py-dist data.py
    - name: Install additional typing data and check with mypy
      run: uv run mypy --install-types --non-interactive lib/ conftest.py pkgfixtures.py tests/

  pyright:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.7.x"
    - name: Install dependencies
      run: uv sync --frozen
    - name: Create a dummy data.py
      run: cp data.py-dist data.py
    - name: Check with pyright
      run: uv run pyright lib/ conftest.py pkgfixtures.py # tests/
