name: Check coding style

on: [push]

jobs:
  pycodestyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.7.x"
    - name: Install dependencies
      run: uv sync --frozen
    - name: flake8
      run: uv run flake8

  pydocstyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.7.x"
    - name: Install dependencies
      run: uv sync --frozen
    - name: pydocstyle
      run: uv run pydocstyle
