name: Check requirements file consistency

on: [push]

jobs:
  requirements-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.7.x"
    - name: Install dependencies
      run: uv sync --frozen
    - run: uv run ./requirements/update_requirements.py
    - run: git diff --exit-code
